name: Invitation
description: I would like to be part of the awesome community
title: "Please invite me to the GitHub Community Organization"
labels: [invite me to the organisation]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
  - type: input
    id: linkedIn
    attributes:
      label: Your LinkedIn (if applicable)
      placeholder: Insert your LinkedIn profile link here
    validations:
      required: false
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: What do you like about this community/Why do you want to join?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thank you for considering joining our GitHub Community Organization!
        Your request will be reviewed shortly.